# Config file .travis.yml

language: python

python:
  - "2.7"

rvm:
  - 1.9.3
  - jruby-19mode
  - 2.1.0

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" RAILS_VERSION=3.2
  - VERSION="7.0" ODOO_REPO="odoo/odoo" RAILS_VERSION=4.0
  - VERSION="7.0" ODOO_REPO="odoo/odoo" RAILS_VERSION=4.1
  - VERSION="7.0" ODOO_REPO="odoo/odoo" RAILS_VERSION=4.2
  - VERSION="8.0" ODOO_REPO="odoo/odoo" RAILS_VERSION=4.2

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/oca/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  #- git clone https://github.com/OCA/connector $HOME/connector -b ${VERSION}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

before_script:
  - cwd=$(pwd)
  - psql -c "CREATE USER openerp WITH PASSWORD 'admin';" -U postgres
  - psql -c 'create database ooor_test with owner openerp;' -U postgres
  - cd ${HOME}/odoo-${VERSION}
  - ./openerp-server --addons-path=${HOME}/odoo-${VERSION}/addons --db_user=postgres --db_user=openerp --db_password=admin --db_host=localhost &
  - cd $cwd
  - bundle install

script:
  - bundle exec rake

services:
  - postgresql

matrix:
  allow_failures:
    - env: "VERSION=8.0"
